global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
    - job_name: 'nodeexporter'
      static_configs:
          - targets: ['node_exporter:9100']
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      basic_auth:
        username: "admin"
        password: "test"
      static_configs:
        - targets: ['appsmith:8080']
